DogLog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dash.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dash/urls.py
from django.urls import path

from . import views

app_name = 'dash'

urlpatterns = [
    path('ajouter', views.ajouter, name='ajouter'),
    path('maps', views.maps, name='maps'),
    path('budget', views.budget, name='budget'),
    path('objectif', views.objectif, name='objectif'),
    path('', views.index, name='index'),
    path('journal', views.journal, name='journal'),
    path('profil', views.profil, name='profil'), 
    path('parametres', views.parametres, name='parametres'),    
    path('logout', views.my_logout, name='logout'),
    path('login', views.my_login, name='login'),
    path('register', views.register, name='register'),
    path('registered', views.registered, name='registered'),
    path('welcome', views.welcome, name='welcome'),
    path('dog_register', views.dog_register, name='dog_register'),
    
]

dash/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User


class Owner(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    age_owner = models.DateField("l'age du maitre", blank=True)
    sex_owner = models.BooleanField('le sexe du maitre', blank=True)
    avatar_owner = models.ImageField(upload_to = 'avatar', blank=True, null=True)
    
    def __str__(self):
        return self.owner.username  

class Breed(models.Model):
    name_breed = models.CharField(max_length=50)    
    
    def __str__(self):
        return self.name_breed    
    
class FoodType(models.Model):
    name_food_type = models.CharField(max_length=50, blank=True, null=True)
    
    
    def __str__(self):
        return self.name_food_type

class FoodBrand(models.Model):
    name_brand = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.name_brand
    
class Photo(models.Model):
    description_photo = models.CharField(max_length=255, blank=True, null=True)
    path_photo = models.ImageField(upload_to='dogs', null=True)
    date_photo = models.DateTimeField('date de publication de photo',default=datetime.datetime.now)
    
    def __str__(self):
        return self.description_photo
        
class Feeding(models.Model):
    quantity = models.IntegerField('Quantité en grams',default=0)
    begin_time = models.DateTimeField("début d'un repas")
    end_time = models.DateTimeField(" fin du repas ")
    comments = models.CharField(max_length=255, blank=True, null=True)
    type = models.ForeignKey(FoodType, on_delete=models.CASCADE, blank=True, null=True)
    brand = models.ManyToManyField(FoodBrand, blank=True)
    photo = models.ManyToManyField(Photo)

    def __str__(self):
        return self.type.name_food_type

class Dog(models.Model):
    FEMALE = 'F'
    MALE = 'M'
    SEXE_CHOICES = [(FEMALE,'femelle'),(MALE,'mâle')]
    name_dog = models.CharField(max_length=50)
    avatar_dog = models.ImageField(upload_to='dog_avatar', null=True, blank=True)
    age_month_dog = models.DateField("l'age du chien en mois")
    sex_dog = models.CharField('mâle ou femelle', choices=SEXE_CHOICES, blank=True, null=True, max_length=20)
    weight_dog = models.FloatField('poids du chien',default=0, null=True, blank=True)
    id_chip_dog = models.BigIntegerField(default=0,  null=True, blank=True)
    sterilized = models.BooleanField('stériliser ou pas')
    breed_dog = models.ForeignKey(Breed, on_delete=models.CASCADE,blank=True, null=True)
    owner = models.ManyToManyField(Owner)
    feed = models.ManyToManyField(Feeding, blank=True)
    photo = models.ManyToManyField(Photo, blank=True)

    def __str__(self):
        return self.name_dog 
        
    
class Vaccine(models.Model):
    name_vacinne = models.CharField(max_length=30)
    date_vaccine = models.DateField('', blank=True, null=True)
    vaccinated = models.BooleanField('yes or no', blank=True, null=True)
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE, blank=True, null=True)   
    
    def __str__(self):
        return self.name_vacinne
    
class WalkType(models.Model):
    name_type_walk = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.name_type_walk

class Walk(models.Model):
    begin_time= models.DateTimeField('date/heure de debut')
    end_time = models.DateTimeField('date/heure defin')
    comments = models.CharField(max_length=200, blank=True, null=True)
    photo_walk = models.ImageField(upload_to='walks', blank= True)
    type = models.ForeignKey(WalkType, on_delete=models.CASCADE )
    dog = models.ManyToManyField(Dog)
    
    def __str__(self):
        return self.type.name_type_walk
    

dash/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db import IntegrityError

from .models import Dog, Walk, WalkType
# Create your views here.

def index(request):
    return render(request, 'dash/index.html')

def journal(request):
    walks = Walk.objects.all()
    return render(request, 'dash/journal.html', {'walks': walks})

def profil(request):
    dogs = Dog.objects.all()
    return render(request, 'dog/profil.html', {'dogs': dogs})


def parametres(request):
    return render(request, 'dash/parametres.html')



def my_login(request):
    return render(request, 'dash/login.html')

def register(request):
    return render(request, 'dash/register.html')

def my_logout(request):
    logout(request)
    return render(request, 'dash/logout.html')

def registered(request):
    name = request.POST['user_name']
    firstname = request.POST['user_firstname']
    pwd = request.POST['user_pwd']
    email = request.POST['user_email']
    username = firstname[0].lower() + "." + name.lower()        
    try:
        user = User.objects.create_user(username, email, pwd)
        user.last_name = name
        user.first_name = firstname
        user.save()
        context = {'user':user}   
        return render(request, 'dash/registered.html', context)            
    except IntegrityError :
        return render(request,'dash/register.html', {'error_message': "le nom d'utilisateur existe déja !"})
    

def welcome(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    context = {'user':user}
    if user is not None:
        login(request, user)
        return render(request, 'dash/welcome.html', context)
    else:
        return render(request, 'dash/error_log.html')


def dog_register(request): 
    # if request.method == 'POST':
    #     form = AddDog(request.POST or None, request.FILES or None)
    #     if form.is_valid():
    #         form.save()
    #     return render(request, 'dog/dog_register.html')
    # else:    
    #     form = AddDog()
    return render(request, 'dog/dog_register.html',)



# dog_name = request.POST['name_dog']






















def ajouter(request):
    return render(request, 'dash/ajouter.html')

def maps(request):
    return render(request, 'dash/maps.html')

def budget(request):
    return render(request, 'dash/budget.html')

def objectif(request):
    return render(request, 'dash/objectif.html')

dash/templates/base/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load active_link_tags %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!--Material icons ( google font icon)-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
    rel="stylesheet">
    <!--Stylesheet-->
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dash/style.css' %}">
    {% endblock %}
</head>
<body>
    <div class="container"><!--left & main & right (grid-columns)-->
        {% include 'base/nav.html' %}
            <main>
                {% block contenue %}
                {% endblock %}
            </main>
        {% include 'base/right.html' %} 

    </div>
    <script src="{% static 'dash/script.js' %}"></script>
</body>
</html>

dash/templates/base/nav.html
{% load static %}
{% load active_link_tags %}
        <aside><!--entire left grid-->
            <div class="top"><!--conteneur (img logo + brandname) qui prend toute la largeur-->
                <div class="logo"><!--img logo + brandname-->
                    <img src="{% static 'dash/images/random/logo.png' %}" alt=""><!--img logo-->
                    <h2>DOG<span class="brandname">LOG</span></h2><!--brandname-->
                </div>
                <div class="close" id="close-btn"><span class="material-icons-round">cancel</span><!--close-btn (hidden in web)-->
                </div>                
            </div>
            <div class="sidebar"><!--contenur du SIDEBAR-->
                <a class="{% active_link 'dash:index' strict=True %}" href="{% url 'dash:index' %}"><span class="material-icons-round">space_dashboard</span><!--icone du SIDEBAR-->
                    <h3>Dashboard</h3>
                </a><!--lien du SIDEBAR-->
                <a class="{% active_link 'dash:journal'  %}" href="{% url 'dash:journal' %}"><span class="material-icons-round">format_list_bulleted</span>
                    <h3>Journal</h3>
                </a>
                <a class="{% active_link 'dash:profil'  %}" href="{% url 'dash:profil' %}"><span class="material-icons-round">pets</span>
                    <h3>Profil</h3>
                </a>
                <!-- <a class="{% active_link 'dash:maps'  %}" href="{% url 'dash:maps' %}"><span class="material-icons-round">place</span>
                    <h3>Maps</h3>
                </a>
                <a class="{% active_link 'dash:budget'  %}" href="{% url 'dash:budget' %}"><span class="material-icons-round">savings</span>
                    <h3>Budget</h3>
                </a>
                <a class="{% active_link 'dash:objectif'  %}" href="{% url 'dash:objectif' %}"><span class="material-icons-round">outlined_flag</span>
                    <h3>Objectif</h3>
                    <span class="objectif-count">2</span>
                </a> -->
                <a class="{% active_link 'dash:parametres'  %}" href="{% url 'dash:parametres' %}"><span class="material-icons-round">settings</span>
                    <h3>Paramètres</h3>
                </a>
                <!-- <a class="{% active_link 'dash:ajouter'  %}" href="{% url 'dash:ajouter' %}"><span class="material-icons-round">add</span>
                    <h3>Ajouter</h3>
                </a> -->
                <a class="{% active_link 'dash:login'  %}" href="{% url 'dash:login' %}"><span class="material-icons-round">login</span>
                    <h3>Connexion</h3>
                </a>
                <a class="{% active_link 'dash:register'  %}" href="{% url 'dash:register' %}"><span class="material-icons-round">person_add</span>
                    <h3>Inscription</h3>
                </a>
                <a class="{% active_link 'dash:logout'  %}" href="{% url 'dash:logout' %}"><span class="material-icons-round">logout</span>
                    <h3>Déconnexion</h3>
                </a>                
            </div>
        </aside>

dash/templates/base/right.html
{% load static %}
{% load active_link_tags %}


<div class="right">
    <div class="top">
        <button id="menu-btn">
            <span class="material-icons-round">menu</span>
        </button>
        <div class="theme-togler">
            <span class="material-icons-round">light_mode</span>
            <span class="material-icons-round">dark_mode</span>
        </div>
        <div class="profile">
            <div class="info">
                <p>Salut, <b>Gokool</b></p>
                <small class="text-muted">Admin</small>
            </div>
            <div class="profile-photo">
                <img src="{% static 'dash/images/random/14.jpg' %}" alt="">
            </div>
        </div>
    </div>
    <!-- FIN DU TOP -->
    

</div>

dash/templates/dash/ajouter.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
{% endblock %}

dash/templates/dash/budget.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
{% endblock %}

dash/templates/dash/error_log.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
<p>Identifiant ou mot de passe incorrect</p>
<a href="{% url 'dash:login' %}">Login</a>
{% endblock %}

dash/templates/dash/index.html
    {% extends 'base/base.html'%}
    {% load static %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dash/style.css' %}">
        {% endblock %}
    {% block contenue %}
        
            <h1>Dashboard</h1>

            <div class="date">
                <input type="datetime-local">
            </div>

            <div class="action"><!--CONTENEUR DES CARDS-->
                <div class="card1"><!--start card 1 -->
                    <span class="material-icons-round">pets</span>
                    <div class="middle">
                        <div class="left">
                            <h3>pets profile</h3>
                            <h1>Django</h1>
                        </div>
                        <div class="right">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="pourcentage">
                                <p>81%</p>
                            </div>
                        </div>
                    </div>
                    <small class="text-muted">un text a remplir</small>
                </div>
                <!---------------------------- END OF CARD 1--------------------------->
                <div class="card2">
                    <span class="material-icons-round">build</span>
                    <div class="middle">
                        <div class="left">
                            <h3>pets profile2</h3>
                            <h1>Django2</h1>
                        </div>
                        <div class="right">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="pourcentage">
                                <p>72%</p>
                            </div>
                        </div>
                    </div>
                    <small class="text-muted">un text a remplir2</small>
                </div>
                <!---------------------------- END OF CARD 2--------------------------->
                <div class="card3">
                    <span class="material-icons-round">favorite</span>
                    <div class="middle">
                        <div class="left">
                            <h3>pets profile3</h3>
                            <h1>Django3</h1>
                        </div>
                        <div class="right">
                            <svg>
                                <circle cx="38" cy="38" r="36"></circle>
                            </svg>
                            <div class="pourcentage">
                                <p>63%</p>
                            </div>
                        </div>
                    </div>
                    <small class="text-muted">un text a remplir3</small>
                </div>
                <!---------------------------- END OF CARD 3--------------------------->
                <div class="card4">
                    <span class="material-icons-round">fingerprint</span>
                    <div class="middle">
                        <div class="left">
                            <h3>pets profile4</h3>
                            <h1>Django4</h1>
                        </div>
                        <div class="right">
                                <svg>
                                    <circle cx="38" cy="38" r="36"></circle>
                                </svg>
                            <div class="pourcentage">
                                <p>54%</p>
                            </div>
                        </div>
                    </div>
                    <small class="text-muted">un text a remplir4</small>
                </div>
                <!---------------- END OF CARD 4--------------------------->
            </div>
        
    {% endblock %}

dash/templates/dash/journal.html
{% extends 'base/base.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'dash/journal.css' %}">
{% endblock %}
{% block contenue %}
    {% for walk in walks %}
    <div class="action1"><!--CONTENEUR DES CARDS-->
        <div class="card"><!--start card 1 -->
            {% for dog in walk.dog.all %}
                <div class="profile-photo">                    
                    <img src="{{dog.avatar_dog.url}}" >
                </div>                
            {% endfor %}             
            <small class="text-muted">begin: {{ walk.begin_time }}</small><br>
            <small class="text-muted">end: {{ walk.end_time }}</small>
            
            <div class="middle">
                <div class="left">
                    <h3>pets profile</h3>
                    <h1>Django</h1>
                </div>
                <div class="right">                   
                    <div class="pourcentage">
                        <p>81%</p>
                    </div>
                </div>
            </div>
            
        </div>
        
            
                     
                    
                        
        </ul>
    </div>    
    {% endfor%}
{% endblock %}

dash/templates/dash/login.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
<form id="login" method="post" action="{% url 'dash:welcome'%}">
    {% csrf_token %}
    <table>
        <tr>
            <td>
                <label for="username">Login</label>
                <input id="username" name="username">
            </td>
            <td>
                <label for="password">Mot de passe</label>
                <input type="password" id="password" name="password">
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="connexion">
            </td>
        </tr>
    </table>
</form>
{% endblock %}

dash/templates/dash/logout.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
<p>A bientôt !</p>
<a href="{% url 'dash:index'%}">index</a>
{% endblock %}

dash/templates/dash/maps.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
{% endblock %}

dash/templates/dash/objectif.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
{% endblock %}

dash/templates/dash/parametres.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
{% endblock %}

dash/templates/dash/register.html
{% extends 'dash/index.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
<form id="register" method="post" action="{% url 'dash:registered' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>
                <label for="user_name">Nom</label>
                <input id="user_name" name="user_name">
            </td>
        </tr>
        <tr>
            <td>
                <label for="user_firstname">Prénom</label>
                <input id="user_firstname" name="user_firstname">
            </td>
        </tr>
        <tr>
            <td>
                <label for="user_email">Email</label>
                <input id="user_email" name="user_email">
            </td>
        </tr>
        <tr>
            <td>
                <label for="user_pwd">Mot de passe</label>
                <input type="password" id="user_pwd" name="user_pwd">
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" value="Enrengistrer">
            </td>
        </tr>
    </table>
</form>
{% if error_message  %}<p><strong>{{ error_message}}</strong></p>{% endif %}
{% endblock %}

dash/templates/dash/registered.html
{% extends 'dash/index.html' %}
{% load active_link_tags %}
{% load static %}
{% load i18n %}

{% block contenue %}


<h1>Bienvenue</h1>
<p>
  <strong>Votre nom d'utilisateur est : {{user.username}}</strong>  
</p>
<a href="{% url 'dash:login' %}">Login</a>
{% endblock %}

dash/templates/dash/welcome.html
{% extends 'dash/index.html' %}
{% load active_link_tags %}
{% load static %}
{% load i18n %}


{% block contenue %}
<h1>Bienvenue {{user.username}} !</h1>
<p>Connexion réussi</p>
<a href="{% url 'dash:index' %}">Page d'acceuil</a>
{% endblock %}

dash/templates/dog/dog_register.html
{% extends 'dash/index.html' %}
{% load active_link_tags %}
{% load static %}
{% load i18n %}

{% block contenue %}
<center>
    <h1>Ajouter un nouveau chien </h1>

    <form id="dog_register" method="POST" action="{% url 'dash:dog_register' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>
                    <label for="name_dog">Nom du chien</label>
                    <input type="text" name="name_dog" id="name_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="avatar_dog">image du chien</label>
                    <input type="image" name="avatar_dog" id="avatar_dog" >
                </td>
            </tr>
            <tr>
                <td>
                    <label for="age_month_dog">l'age du chien</label>
                    <input type="date" name="age_month_dog" id="age_month_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="sex_dog">sexe du chien</label>
                    <input type="text" name="sex_dog" id="sex_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="weight_dog">le poids du chien</label>
                    <input type="number" name="weight_dog" id="weight_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="id_chip_dog">l'identification par puce </label>
                    <input type="text" name="id_chip_dog" id="id_chip_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="sterilized">steriliser ? :</label>
                    <input type="text" name="sterilized" id="sterilized">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="breed_dog">race du chien</label>
                    <input type="text" name="breed_dog" id="breed_dog">
                </td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Envoyer">
                </td>
            </tr>
        </table>
    </form>
</center>    
{% endblock %}

dash/templates/dog/profil.html
{% extends 'base/base.html' %}
{% load static %}
{% load active_link_tags %}
{% load i18n %}

{% block contenue %}
    
        {% for dog in dogs %}
            <div class="profile">
                <div class="info">
                    <p>Salut, <b>{{ dog.name_dog }}</b></p>
                    <small class="text-muted">{{ dog.sex_dog }}</small>
                </div>
                <div class="profile-photo">
                    <img src="{{ dog.avatar_dog.url }}" >
                </div>
            </div>         
        {% endfor%}
    
{% endblock %}